# Generated by Django 6.0 on 2025-12-11 21:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(help_text='Título de la certificación', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción de la certificación', null=True)),
                ('level', models.IntegerField(choices=[(0, 'Sin Certificar'), (1, 'Novato'), (2, 'Aprendiz'), (3, 'Competente'), (4, 'Avanzado'), (5, 'Experto')], default=0, help_text='Nivel de habilidad certificado', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_score', models.FloatField(default=0, help_text='Puntaje total obtenido (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('assessments_completed', models.IntegerField(default=0, help_text='Número de evaluaciones completadas')),
                ('evidence_links', models.TextField(blank=True, help_text='Enlaces a evidencias (JSON)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activa'), ('expired', 'Expirada'), ('revoked', 'Revocada')], default='active', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de emisión')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificación',
                'verbose_name_plural': 'Certificaciones',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['user', '-issued_at'], name='certificati_user_id_53ca00_idx'), models.Index(fields=['status', '-issued_at'], name='certificati_status_593094_idx'), models.Index(fields=['level', '-total_score'], name='certificati_level_e3010c_idx')],
            },
        ),
    ]
