# Generated by Django 6.0 on 2025-12-12 14:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener exactamente 10 dígitos.', regex='^\\d{10}$')], verbose_name='Teléfono')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/', verbose_name='Logo')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Industria')),
                ('size', models.CharField(choices=[('small', '1-50 empleados'), ('medium', '51-200 empleados'), ('large', '201-1000 empleados'), ('enterprise', '1000+ empleados')], default='small', max_length=20, verbose_name='Tamaño')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('administrators', models.ManyToManyField(blank=True, related_name='administered_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Administradores')),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'empresa'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('project', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proyecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('members', models.ManyToManyField(blank=True, related_name='team_members', to=settings.AUTH_USER_MODEL, verbose_name='Miembros')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='organizations.organization', verbose_name='Organización')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL, verbose_name='Líder del equipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
